export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
};

export const taskConstants = {
  GET_ALL_TASK_SUCCESS: "GET_ALL_TASK_SUCCESS",
  GET_ALL_TASK_FAILURE: "GET_ALL_TASK_FAILURE",
  GET_ALL_TASK_REQUEST: "GET_ALL_TASK_REQUEST",

  GET_SINGLE_SUCCESS: "GET_SINGLE_SUCCESS",
  GET_SINGLE_FAILURE: "GET_SINGLE_FAILURE",
  GET_SINGLE_REQUEST: "GET_SINGLE_REQUEST",

  UPDATE_SINGLE_SUCCESS: "UPDATE_SINGLE_SUCCESS",
  UPDATE_SINGLE_FAILURE: "UPDATE_SINGLE_FAILURE",
  UPDATE_SINGLE_REQUEST: "UPDATE_SINGLE_REQUEST",

  DELETE_SINGLE_SUCCESS: "DELETE_SINGLE_SUCCESS",
  DELETE_SINGLE_FAILURE: "DELETE_SINGLE_FAILURE",
  DELETE_SINGLE_REQUEST: "DELETE_SINGLE_REQUEST",

  CREATE_SINGLE_SUCCESS: "CREATE_SINGLE_SUCCESS",
  CREATE_SINGLE_FAILURE: "CREATE_SINGLE_FAILURE",
  CREATE_SINGLE_REQUEST: "CREATE_SINGLE_REQUEST",

  CLEAR_SINGLE_TASK: "CLEAR_SINGLE_TASK",
  CLEAR_DATA: "CLEAR_DATA",
};
